pipeline {
    agent any
    stages {
        stage('Checkout') {
            agent {label "builder"}
            steps {
                echo "\u2600 Getting source"
                // Get code
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/master']],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [[$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: true, recursiveSubmodules: true, reference: '', trackingSubmodules: false]],
                          submoduleCfg: [],
                          userRemoteConfigs: [[credentialsId: 'fb82a473-e4f4-4f14-b0d5-0f28af79d0ca', url: 'git@rnd-github-usa-g.huawei.com:SeattleCloudBU/DFV_K2_SeaStar.git']]
                        ])
            }
        }
        stage('Build Builder Image') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Building Docker Builder Image"
                sh "make -C K2Build builder_img_build"
                sh "make -C K2Build builder_img_push"
            }
        }
        stage('Configure') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Building"
                sh "./K2Build/k2build make -C K2Build configure"
            }
        }
        stage('Build') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Building"
                sh "./K2Build/k2build make -C K2Build build"
            }
        }
        stage('Install') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Building"
                sh "./K2Build/k2build make -C K2Build install"
            }
        }
        stage('Test') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Test"
                sh "./K2Build/k2build make -C K2Build test"
            }
        }
        stage('Package') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Test"
                sh "./K2Build/k2build make -C K2Build package"
            }
        }
        stage('Upload artifacts') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Uploading artifacts"
                sh "curl http://k2-bvu-10001.huawei.com:10080/incoming/ --upload-file libseastar-k2_*.deb"
                sh "curl http://k2-bvu-10001.huawei.com:10080/incoming/ --upload-file libseastar-k2_*.changes"
		sh "curl http://k2-bvu-10001.huawei.com:10070/ --upload-file libseastar-k2-*.rpm"
                sh "curl http://k2-bvu-10001.huawei.com:10070/commit"
            }
        }
        stage('Clean') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Cleaning"
                sh "./K2Build/k2build make -C K2Build clean"
            }
        }
        stage('Configure Debug') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Building"
                sh "./K2Build/k2build make -C K2Build configure-dbg"
            }
        }
        stage('Build Debug') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Building"
                sh "./K2Build/k2build make -C K2Build build-dbg"
            }
        }
        stage('Install Debug') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Building"
                sh "./K2Build/k2build make -C K2Build install-dbg"
            }
        }
        stage('Test Debug') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Test"
                sh "./K2Build/k2build make -C K2Build test-dbg"
            }
        }
        stage('Package Debug') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Test"
                sh "./K2Build/k2build make -C K2Build package-dbg"
            }
        }
        stage('Upload Debug artifacts') {
            options { skipDefaultCheckout() }
            agent {label "builder"}
            steps {
                echo "\u2600 Uploading artifacts"
                sh "curl http://k2-bvu-10001.huawei.com:10080/incoming/ --upload-file libseastar-dbg-k2_*.deb"
                sh "curl http://k2-bvu-10001.huawei.com:10080/incoming/ --upload-file libseastar-dbg-k2_*.changes"
            }
        }

    }
}
