#!/bin/bash
# This script executes a command using the builder docker image
topname=$(dirname "$0")
cd ${topname}/..
echo ">>> Using docker"
# set interactive docker only if we're running inside a terminal
if [ -t 1 ] ; then IT=-it; else IT=; fi
echo ">>> Pulling latest builder image"
docker pull k2-bvu-10001.huawei.com/k2seastar_builder:latest
echo ">>> Executing command \"$*\" in the build container"
docker run --init --rm ${IT} -v "${PWD}:/build" k2-bvu-10001.huawei.com/k2seastar_builder:latest "$@"
